# Generated by Django 5.2 on 2025-08-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_rating', to='subscribe.subscribe')),
            ],
            options={
                'db_table': 'coachrating_coachrating',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__range', (1, 5)), ('rating__isnull', True), _connector='OR'), name='rating_between_1_and_5')],
            },
        ),
    ]
