# Generated by Django 5.2 on 2025-07-22 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='items',
            field=models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
