# Generated by Django 5.2 on 2025-07-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_run.run')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
