# Generated by Django 5.2 on 2025-07-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latitudelongitude', '0002_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
