# Generated by Django 5.2 on 2025-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0002_remove_athleteinfo_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteinfo',
            name='weight',
            field=models.FloatField(default=None),
        ),
    ]
