# Generated by Django 5.2 on 2025-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0006_alter_athleteinfo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
