# Generated by Django 5.2 on 2025-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0007_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
