# Generated by Django 5.2 on 2025-07-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0008_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='athlete_info.athleteinfo')),
            ],
        ),
    ]
