# Generated by Django 5.2 on 2025-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0010_alter_challengeathlete_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
