# Generated by Django 5.2 on 2025-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_info', '0011_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeathlete',
            options={'ordering': ['full_name']},
        ),
    ]
