# Generated by Django 5.2 on 2025-07-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
        ('the_athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='athlete_data',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='the_athlete.athlete'),
        ),
    ]
