# Generated by Django 5.2 on 2025-07-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_athlete_data'),
        ('the_athlete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='athlete_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='the_athlete.athlete'),
        ),
    ]
