# Generated by Django 5.2 on 2025-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
