# Generated by Django 5.2 on 2025-07-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_run_athlete_data'),
        ('the_athlete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='athlete_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_athlete.athlete'),
        ),
    ]
