# Generated by Django 5.2 on 2025-07-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_run_athlete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='athlete_data',
        ),
    ]
